name: CI/CD with Rome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Run Rome Linting
        run: npx rome check . --apply

      - name: Run Rome Formatting
        run: npx rome format

      - name: Build Project
        run: npm run build

      # Deploy ke Vercel
      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
