name: CI/CD to VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Rome Linting
        run: npx rome check . --apply || true

      - name: Run Rome Formatting
        run: npx rome format .

      - name: Build Project
        run: npm run build

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KAWUNG_SSH_KEY }}
        env:
          SSH_PASSPHRASE: ${{ secrets.KAWUNG_SSH_PASSPHRASE }}

      - name: SSH to VM and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.KAWUNG_USERNAME }}@${{ secrets.KAWUNG_HOST }} -p ${{ secrets.KAWUNG_PORT }} << EOF
          cd frontend 
          git pull
          npm install
          npm run build
          pm2 restart frontend  
          sudo systemctl restart gunicorn
          EOF
        env:
          KAWUNG_USERNAME: ${{ secrets.KAWUNG_USERNAME }}
          KAWUNG_HOST: ${{ secrets.KAWUNG_HOST }}
          KAWUNG_PORT: ${{ secrets.KAWUNG_PORT }}
